kind: Service
apiVersion: v1
metadata:
  name: react-test-service
spec:
  selector:
    app: react-test
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-test
  labels:
    app: react-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-test
  template:
    metadata:
      labels:
        app: react-test
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: react-test
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
